
if [[ -s "${HOME}/.zprezto/init.zsh" ]]; then
  source "${HOME}/.zprezto/init.zsh"
fi

source "${HOME}/.dotfiles/zsh/zsh_conf/aliases.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/fasd.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/functions.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/keybindings.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/path.zsh"

setopt interactivecomments

. $HOME/.asdf/asdf.sh
