
if [[ -s "${HOME}/.zprezto/init.zsh" ]]; then
  source "${HOME}/.zprezto/init.zsh"
fi

source "${HOME}/.dotfiles/zsh/zsh_conf/aliases.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/fasd.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/functions.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/keybindings.zsh"
source "${HOME}/.dotfiles/zsh/zsh_conf/path.zsh"
if [ -f "$HOME/perl5/perlbrew/etc/bashrc" ]; then
  source "$HOME/perl5/perlbrew/etc/bashrc"
fi

setopt interactivecomments

export ANDROID_SDK=/Users/imoghul/Library/Android/sdk

. $HOME/.asdf/asdf.sh
